language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - python3 scraper.py
before_install:
  - chmod +x push.sh  
after_success:
  - ./push.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: results
  on:
    branch: master